# 
# The pipeline for testing PublishBuildArtifact Task
# Issue description:
# When there is a '+' sign in Artifact's name - the part of artifact cannot be downloaded

trigger: none

pool: 
  name: Default
  demands:
    - agent.name -equals TestBuildArtifact

#pool: 
#    vmImage: 'ubuntu-latest'

steps:
# Old version with issue
- task: PublishBuildArtifacts@1
  name: 'Old_PublishBuildArtifacts'
  inputs:
    PathtoPublish: '$(Pipeline.Workspace)'
    ArtifactName: 'ArtifactWithIssue+32487'
    publishLocation: 'Container'
# New version without issue
- task: LiliaPublishBuildArtifacts@1
  name: 'New_PublishBuildArtifacts'
  inputs:
    PathtoPublish: '$(Pipeline.Workspace)'
    ArtifactName: 'ArtifactWithoutIssue+32487'
    publishLocation: 'Container'

# New version without issue
- task: LiliaPublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Pipeline.Workspace)'
    ArtifactName: 'FileArtifactWithoutIssue+32487'
    publishLocation: 'FilePath'
    TargetPath: '$(Pipeline.Workspace)'
