trigger: none

#pool: 
#  name: Default
#  demands:
#    - agent.name -equals TestBuildArtifact

pool: 
    vmImage: 'windows-latest'

variables:
    DownloadBuildArtifacts.ForceEnableDownloadZipForCanary : 'true'

steps:

    
- task: PublishBuildArtifacts@1
  name: 'PublishBuildArtifacts1_drop_9234857_2'
  condition: always()
  inputs:
    PathtoPublish: '$(Pipeline.Workspace)'
    ArtifactName: 'drop ! 9234857'
    publishLocation: 'Container'


- task: DownloadBuildArtifacts@0 #.206.0
  condition: always()
  inputs:
    buildType: 'current'
    downloadType: 'single'
    artifactName: 'drop ! 9234857'
    downloadPath: '$(System.ArtifactsDirectory)'


- task: PublishBuildArtifacts@1
  name: 'PublishBuildArtifacts1_drop_9234857_3'
  condition: always()
  inputs:
    PathtoPublish: '$(Pipeline.Workspace)'
    ArtifactName: 'drop @ 9234857'
    publishLocation: 'Container'


- task: DownloadBuildArtifacts@0 #.206.0
  condition: always()
  inputs:
    buildType: 'current'
    downloadType: 'single'
    artifactName: 'drop @ 9234857'
    downloadPath: '$(System.ArtifactsDirectory)'

    
- task: PublishBuildArtifacts@1
  name: 'PublishBuildArtifacts1_drop_9234857_4'
  condition: always()
  inputs:
    PathtoPublish: '$(Pipeline.Workspace)'
    ArtifactName: 'drop # 9234857'
    publishLocation: 'Container'


- task: DownloadBuildArtifacts@0 #.206.0
  condition: always()
  inputs:
    buildType: 'current'
    downloadType: 'single'
    artifactName: 'drop # 9234857'
    downloadPath: '$(System.ArtifactsDirectory)'


    
- task: PublishBuildArtifacts@1
  name: 'PublishBuildArtifacts1_drop_9234857_5'
  condition: always()
  inputs:
    PathtoPublish: '$(Pipeline.Workspace)'
    ArtifactName: 'drop % 9234857'
    publishLocation: 'Container'


- task: DownloadBuildArtifacts@0 #.206.0
  condition: always()
  inputs:
    buildType: 'current'
    downloadType: 'single'
    artifactName: 'drop ^ 9234857'
    downloadPath: '$(System.ArtifactsDirectory)'

    
- task: PublishBuildArtifacts@1
  name: 'PublishBuildArtifacts1_drop_9234857_6'
  condition: always()
  inputs:
    PathtoPublish: '$(Pipeline.Workspace)'
    ArtifactName: 'drop ^ 9234857'
    publishLocation: 'Container'


- task: PublishBuildArtifacts@1
  name: 'PublishBuildArtifacts1_drop_9234857_7'
  condition: always()
  inputs:
    PathtoPublish: '$(Pipeline.Workspace)'
    ArtifactName: 'drop:9234857'
    publishLocation: 'Container'


- task: DownloadBuildArtifacts@0 #.206.0
  condition: always()
  inputs:
    buildType: 'current'
    downloadType: 'single'
    artifactName: 'drop:9234857'
    downloadPath: '$(System.ArtifactsDirectory)'


- task: PublishBuildArtifacts@1
  name: 'PublishBuildArtifacts1_drop_9234857_8'
  condition: always()
  inputs:
    PathtoPublish: '$(Pipeline.Workspace)'
    ArtifactName: 'drop ? 9234857'
    publishLocation: 'Container'


- task: DownloadBuildArtifacts@0 #.206.0
  condition: always()
  inputs:
    buildType: 'current'
    downloadType: 'single'
    artifactName: 'drop ? 9234857'
    downloadPath: '$(System.ArtifactsDirectory)'


- task: PublishBuildArtifacts@1
  name: 'PublishBuildArtifacts1_drop_9234857_9'
  condition: always()
  inputs:
    PathtoPublish: '$(Pipeline.Workspace)'
    ArtifactName: 'drop () 9234857'
    publishLocation: 'Container'


- task: DownloadBuildArtifacts@0 #.206.0
  condition: always()
  inputs:
    buildType: 'current'
    downloadType: 'single'
    artifactName: 'drop () 9234857'
    downloadPath: '$(System.ArtifactsDirectory)'

- task: DownloadBuildArtifacts@0 #.206.0
  inputs:
    buildType: 'specific'
    project: '3e0295ab-3dd6-43ce-86af-16273f5f1b23'
    pipeline: '33'
    buildVersionToDownload: 'latest'
    allowPartiallySucceededBuilds: true
    downloadType: 'single'
    artifactName: 'drop & 9234857'
    downloadPath: '$(System.ArtifactsDirectory)'


