# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java
trigger: none

pool: 
  name: Default
  demands:
    - agent.name -equals Telem_13.02

#    vmImage: 'ubuntu-latest'

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.18'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/surefire-reports/TEST-*.xml'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Pipeline.Workspace)'
    artifact: 'Artifact+98437'
    publishLocation: 'pipeline'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Pipeline.Workspace)'
    ArtifactName: 'drop+9234857'
    publishLocation: 'Container'

- task: PublishPipelineArtifact@0
  inputs:
    artifactName: 'art+9348275'
    targetPath: '$(Pipeline.Workspace)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Pipeline.Workspace)'
    ArtifactName: 'drop+9234857'
    publishLocation: 'Container'

- task: LiliaPublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Pipeline.Workspace)'
    ArtifactName: 'Liliadrop+9234857'
    publishLocation: 'Container'
    
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Pipeline.Workspace)'
    ArtifactName: 'drop9234857'
    publishLocation: 'Container'
