trigger: none

jobs:
- job: 'Self_Hosted'
  displayName: 'Self-Hosted'  
  pool: Default

  steps:

  # publish artifact to container
  - task: PublishBuildArtifactsLiliaS@1
    name: 'Pipeline_PublishBuildArtifactsLiliaS'
    displayName: 'Publish To Container'
    condition: always()
    timeoutInMinutes: 1
    #env:
    #  TASKS_ENABLE_BUILDARTIFACTS_PLUS_SIGN_WORKAROUND: false
    inputs:
      PathtoPublish: '$(Build.SourcesDirectory)/src'
      ArtifactName: 'drop + 9234857 NoZip'
      publishLocation: 'Container'

  # download artifact from container
  - task: DownloadBuildArtifactsLiliaS@0 #.206.0
    name: 'Pipeline_DownloadBuildArtifactsLiliaS'
    displayName: 'Download From Container'
    condition: always()
    timeoutInMinutes: 1
    #env:
    #  TASKS_ENABLE_BUILDARTIFACTS_PLUS_SIGN_WORKAROUND: false
    inputs:
      buildType: 'current'
      downloadType: 'single'
      artifactName: 'drop + 9234857 NoZip'
      downloadPath: '$(System.ArtifactsDirectory)'
