trigger: none

# variables:
#  AZP_TASK_FF_ENABLE_BUILDARTIFACTS_PLUS_SIGN_WORKAROUND: true

jobs:
- job: 'Self_Hosted'
  displayName: 'Self-Hosted'  
  pool: Default

  steps:

  # publish artifact to container
  - task: PublishBuildArtifacts@1  
    #env:
    #  AZP_TASK_FF_ENABLE_BUILDARTIFACTS_PLUS_SIGN_WORKAROUND: false
    name: 'Pipeline_PublishBuildArtifacts'
    displayName: 'Publish To Container'
    condition: always()
    timeoutInMinutes: 1
    #env:
    #  AZP_TASK_FF_ENABLE_BUILDARTIFACTS_PLUS_SIGN_WORKAROUND: true
    inputs:
      PathtoPublish: '$(Build.SourcesDirectory)/src'
      ArtifactName: 'drop . 9234857 NoZip'
      publishLocation: 'Container'

  # download artifact from container
  - task: DownloadBuildArtifacts@0 #.206.0
    #env:
    #  AZP_TASK_FF_ENABLE_BUILDARTIFACTS_PLUS_SIGN_WORKAROUND: false
    name: 'Pipeline_DownloadBuildArtifacts'
    displayName: 'Download From Container'
    condition: always()
    timeoutInMinutes: 1
    inputs:
      buildType: 'current'
      downloadType: 'single'
      artifactName: 'drop . 9234857 NoZip'
      downloadPath: '$(System.ArtifactsDirectory)'
