trigger: none

#variables:
#  AZP_TASK_FF_ENABLE_BUILDARTIFACTS_PLUS_SIGN_WORKAROUND: "True"

parameters:
- name: runmshosted
  default: false
  displayName: Run MS-Hosted
  type: boolean
- name: runselfhosted
  default: true
  displayName: Run Self-Hosted
  type: boolean
  # just more steps to run, less steps - for testing pipeline is ok
  # FIRST RUN - with default parameters, SECOND RUN - enable moreoptions, THIRD RUN - enable fileshare !!!
- name: moreoptions
  default: false
  displayName: Run Many
  type: boolean
  # enable file path artifacts
  # FIRST RUN - with default parameters, SECOND RUN - enable moreoptions, THIRD RUN - enable fileshare !!!
- name: fileshare
  default: false
  displayName: Enable File Path Artifacts
  type: boolean

jobs:

- job: 'Self_Hosted'
  condition: ${{ parameters.runselfhosted }}
  displayName: 'Self-Hosted'  
  pool: Default
  strategy:
    matrix:
      #'Artifact with + NoZip':
      #  artifactName: 'drop.9234857NoZip'
      'Artifact with + Zip':
        artifactName: 'drop.9234857Zip'
        DownloadBuildArtifacts.ForceEnableDownloadZipForCanary : 'true'
      #'Artifact with .':
      #  artifactName: 'drop . 9234857'

## STEPS ARE THE SAME FOR BOTH JOBS: MS_Hosted and Self_Hosted
  steps:

  # publish artifact to container
  - task: PublishBuildArtifacts@1
    name: 'Pipeline_PublishBuildArtifacts'
    displayName: 'Publish To Container'
    condition: always()
    timeoutInMinutes: 1
    inputs:
      PathtoPublish: '$(Build.SourcesDirectory)/src'
      ArtifactName: $(artifactName)
      publishLocation: 'Container'

  # download artifact from container
  - task: DownloadBuildArtifacts@0 #.206.0
    name: 'Pipeline_DownloadBuildArtifacts'
    displayName: 'Download From Container'
    condition: always()
    timeoutInMinutes: 1
    inputs:
      buildType: 'current'
      downloadType: 'single'
      artifactName: $(artifactName)
      downloadPath: '$(System.ArtifactsDirectory)'

  # publish artifact to file path
  # file path option is only possible for Windows
  - task: PublishBuildArtifacts@1
    name: 'FileShare_PublishBuildArtifacts'
    displayName: 'Publish To File Path'
    condition: ${{ parameters.fileshare }}
    timeoutInMinutes: 1
    inputs:
      PathtoPublish: '$(Build.SourcesDirectory)/src'
      ArtifactName: '$(artifactName)2'
      publishLocation: 'FilePath'
      TargetPath: '$(Pipeline.Workspace)'

  # download artifact from file path
  # file path option is only possible for Windows
  - task: DownloadBuildArtifacts@0 #.206.0
    name: 'FileShare_DownloadBuildArtifacts'
    displayName: 'Download From File Path'
    condition: ${{ parameters.fileshare }}
    timeoutInMinutes: 1
    inputs:
      buildType: 'current'
      downloadType: 'single'
      artifactName: '$(artifactName)2'
      downloadPath: '$(System.ArtifactsDirectory)'

  # download multiple artifacts from this build
  - task: DownloadBuildArtifacts@0
    name: 'All_DownloadBuildArtifacts'
    displayName: 'Multiple Download From This Build'
    condition: and (always(), ${{ parameters.moreoptions }})
    timeoutInMinutes: 1
    inputs:
      buildType: 'current'
      downloadType: 'specific'
      itemPattern: '**/*.yml'
      downloadPath: '$(System.ArtifactsDirectory)'

  # download multiple artifacts from previous run of this build
  - task: DownloadBuildArtifacts@0
    name: 'All_Previous_DownloadBuildArtifacts'
    displayName: 'Multiple Download From Other Build'
    condition: and (always(), ${{ parameters.moreoptions }})
    timeoutInMinutes: 1
    inputs:
      buildType: 'specific'
      project: '8e990140-cc7d-4067-90bf-5ea049bb3fc1'
      pipeline: '2'
      buildVersionToDownload: 'latest'
      allowPartiallySucceededBuilds: true
      downloadType: 'specific'
      itemPattern: '**/*.yml'
      downloadPath: '$(System.ArtifactsDirectory)'

  # download single artifact from previous run of this build
  - task: DownloadBuildArtifacts@0
    name: 'Previous_DownloadBuildArtifacts'
    displayName: 'Single Download From Other Build'
    condition: and (always(), ${{ parameters.moreoptions }})
    timeoutInMinutes: 1
    inputs:
      buildType: 'specific'
      project: '8e990140-cc7d-4067-90bf-5ea049bb3fc1'
      pipeline: '2'
      buildVersionToDownload: 'latest'
      allowPartiallySucceededBuilds: true
      downloadType: 'single'
      artifactName: '$(artifactName)'
      downloadPath: '$(System.ArtifactsDirectory)'
