trigger: none

#pool: 
#  name: Default
#  demands:
#    - agent.name -equals TestBuildArtifact

pool: 
    vmImage: 'ubuntu-latest'

steps:

- task: PublishBuildArtifacts@1
  name: 'PublishBuildArtifacts1_drop_9234857'
  inputs:
    PathtoPublish: '$(Pipeline.Workspace)'
    ArtifactName: '
    publishLocation: 'Container'

#- task: LiliaPublishBuildArtifacts@1
#  name: 'LiliaPublishBuildArtifacts1_Liliadrop_9234857'
#  inputs:
#    PathtoPublish: '$(Pipeline.Workspace)'
#    ArtifactName: '2_Liliadrop+9234857'
#    publishLocation: 'Container'

- task: DownloadBuildArtifacts@1
  inputs:
    buildType: 'current'
    downloadType: 'single'
    downloadPath: '$(System.ArtifactsDirectory)'