# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

jobs:

- job: 'DownloadPackageTest'
  strategy:
    matrix:
      linux:
        imageName: 'ubuntu-latest'
      mac:
        imageName: 'macOS-latest'
      windows:
        imageName: 'windows-latest'
      self:
        pool: Default

  steps:
#  - task: Maven@3
#    inputs:
#      mavenPomFile: 'pom.xml'
#      mavenOptions: '-Xmx3072m'
#      javaHomeOption: 'JDKVersion'
#      jdkVersionOption: '1.8'
#      jdkArchitectureOption: 'x64'
#      publishJUnitResults: true
#      testResultsFiles: '**/surefire-reports/TEST-*.xml'
#      goals: 'package'

#  - task: DownloadPackage@1
#    inputs:
#      packageType: 'npm'
#      feed: '3e0295ab-3dd6-43ce-86af-16273f5f1b23/733a8840-9cef-412b-9bb0-8947825ed8b7'
#      view: '4e4e8545-8f17-43b5-96e7-7bd672f8cebd'
#      definition: 'a4b9c615-31e5-4a66-9567-8b05ea4e9eca'
#      version: '1.1.0'
#      downloadPath: '$(System.ArtifactsDirectory)'

  - task: DownloadPackageLiliya@1
    inputs:
      packageType: 'npm'
      feed: '3e0295ab-3dd6-43ce-86af-16273f5f1b23/733a8840-9cef-412b-9bb0-8947825ed8b7'
      view: '4e4e8545-8f17-43b5-96e7-7bd672f8cebd'
      definition: 'a4b9c615-31e5-4a66-9567-8b05ea4e9eca'
      version: '1.1.0'
      downloadPath: '$(System.ArtifactsDirectory)/L1'