# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java
trigger: none

#pool: 
#  name: Default
#  demands:
#    - agent.name -equals TestBuildArtifact

variables:
- name: artifactName1
  value: '1_drop+9234857'
- name: artifactName2
  value: '2_Liliadrop+9234857'
- name: artifactName3
  value: '3_drop&9234857'



pool: 
    vmImage: 'ubuntu-latest'

steps:
#- task: Maven@3
#  inputs:
#    mavenPomFile: 'pom.xml'
#    mavenOptions: '-Xmx3072m'
#    javaHomeOption: 'JDKVersion'
#    jdkVersionOption: '1.18'
#    jdkArchitectureOption: 'x64'
#    publishJUnitResults: true
#    testResultsFiles: '**/surefire-reports/TEST-*.xml'
#    goals: 'package'

#- task: PublishTestResults@2
#  inputs:
#    testResultsFormat: 'JUnit'
#    testResultsFiles: '**/surefire-reports/TEST-*.xml'

- task: PublishBuildArtifacts@1
  name: 'A1_PublishBuildArtifacts1'
  condition: always()
  inputs:
    PathtoPublish: '$(Pipeline.Workspace)'
    ArtifactName: ${{ variables.artifactName1 }}
    publishLocation: 'Container'

- task: LiliaPublishBuildArtifacts@1
  name: 'A2_LiliaPublishBuildArtifacts1'
  condition: always()
  inputs:
    PathtoPublish: '$(Pipeline.Workspace)'
    ArtifactName: ${{ variables.artifactName2 }}
    publishLocation: 'Container'

- task: PublishBuildArtifacts@1
  name: 'A3_PublishBuildArtifacts1'
  condition: always()
  inputs:
    PathtoPublish: '$(Pipeline.Workspace)'
    ArtifactName: ${{ variables.artifactName3 }}
    publishLocation: 'Container'

- task: DownloadBuildArtifacts@1
  name: 'A1_DownloadBuildArtifacts1'
  condition: always()
  inputs:
    buildType: 'current'
    downloadType: 'single'
    artifactName: ${{ variables.artifactName1 }}
    downloadPath: '$(System.ArtifactsDirectory)'

- task: DownloadBuildArtifacts@1
  name: 'A2_DownloadBuildArtifacts1'
  condition: always()
  inputs:
    buildType: 'current'
    downloadType: 'single'
    artifactName: ${{ variables.artifactName2 }}
    downloadPath: '$(System.ArtifactsDirectory)'

- task: DownloadBuildArtifacts@1
  name: 'A3_DownloadBuildArtifacts1'
  condition: always()
  inputs:
    buildType: 'current'
    downloadType: 'single'
    artifactName: ${{ variables.artifactName3 }}
    downloadPath: '$(System.ArtifactsDirectory)'



#- task: PublishPipelineArtifact@1
#name: 'PublishPipelineArtifact@1
#  inputs:
#    targetPath: '$(Pipeline.Workspace)'
#    artifact: '4_Artifact+98437'
#    publishLocation: 'pipeline'

#- task: PublishBuildArtifacts@1
#  inputs:
#    PathtoPublish: '$(Pipeline.Workspace)'
#    ArtifactName: 'drop+9234857'
#    publishLocation: 'Container'

#- task: PublishPipelineArtifact@0
#  inputs:
#    artifactName: 'art+9348275'
#    targetPath: '$(Pipeline.Workspace)'