trigger: none

# variables:
#  AZP_TASK_FF_ENABLE_BUILDARTIFACTS_PLUS_SIGN_WORKAROUND: true
variables:
- name: artifactname
  value: 'drop.9234857.pep'
- name: DownloadBuildArtifacts.ForceEnableDownloadZipForCanary
  value: 'true'

  

jobs:
- job: 'Self_Hosted'
  displayName: 'Self-Hosted'
  pool: Default
#- job: 'MS_Hosted'
#  displayName: 'MS-Hosted'
#  pool:
#    vmImage: windows-latest


  steps:
#-------------------------------------------------------------------------
  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(Build.SourcesDirectory)/src'
      artifact: 'drop.32875.gdf'
      publishLocation: 'pipeline'

  - task: DownloadPipelineArtifact@2
    inputs:
      buildType: 'current'
      artifactName: 'drop.32875.gdf'
      targetPath: '$(Pipeline.Workspace)'
#-------------------------------------------------------------------------


  # publish artifact to container
  - task: PublishBuildArtifacts@1  
    #env:
    #  AZP_TASK_FF_ENABLE_BUILDARTIFACTS_PLUS_SIGN_WORKAROUND: false
    name: 'Pipeline_PublishBuildArtifacts'
    displayName: 'Publish To Container'
    condition: always()
    timeoutInMinutes: 1
    #env:
    #  AZP_TASK_FF_ENABLE_BUILDARTIFACTS_PLUS_SIGN_WORKAROUND: true
    inputs:
      PathtoPublish: '$(Build.SourcesDirectory)/src'
      ArtifactName: ${{ variables.artifactname }}
      publishLocation: 'Container'

  # download artifact from container
  - task: DownloadBuildArtifacts@0 #.206.0
    #env:
    #  AZP_TASK_FF_ENABLE_BUILDARTIFACTS_PLUS_SIGN_WORKAROUND: false
    name: 'Pipeline_DownloadBuildArtifacts'
    displayName: 'Download From Container'
    condition: always()
    timeoutInMinutes: 1
    inputs:
      buildType: 'current'
      downloadType: 'single'
      artifactName: ${{ variables.artifactname }}
      downloadPath: '$(System.ArtifactsDirectory)'
