trigger: none

#pool: 
#  name: Default
#  demands:
#    - agent.name -equals TestBuildArtifact

pool: 
    vmImage: 'windows-latest'

variables:
    DownloadBuildArtifacts.ForceEnableDownloadZipForCanary : 'true'

steps:

- task: PublishBuildArtifacts@1
  name: 'PublishBuildArtifacts1_drop_9234857'
  inputs:
    PathtoPublish: '$(Pipeline.Workspace)'
    ArtifactName: 'drop & 9234857'
    publishLocation: 'Container'


#- task: DownloadBuildArtifacts@0
#  inputs:
#    buildType: 'specific'
#    project: '3e0295ab-3dd6-43ce-86af-16273f5f1b23'
#    pipeline: '33'
#    buildVersionToDownload: 'latest'
#    downloadType: 'single'
#    artifactName: 'drop & 9234857'
#    downloadPath: '$(System.ArtifactsDirectory)'


#- task: DownloadBuildArtifacts@0 #.206.0
#  inputs:
#    buildType: 'current'
#    downloadType: 'single'
#    artifactName: 'drop & 9234857'
#    downloadPath: '$(System.ArtifactsDirectory)'
