# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger: none

jobs:

- job: 'BatchTest'
  pool:
    vmImage: windows-latest
  steps:
  - template: src/batch/templates/basic-steps.yml

- job: 'MavenTest'
  strategy:
    matrix:
      linux:
        imageName: 'ubuntu-latest'
      mac:
        imageName: 'macOS-latest'
      windows:
        imageName: 'windows-latest'

  steps:
  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.8'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      goals: 'package'

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/TEST-*.xml'

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(Pipeline.Workspace)/s/pom.xml'
      artifact: 'Artifact-$(imageName)'
      publishLocation: 'pipeline'

  - task: DownloadPipelineArtifact@2
    inputs:
      buildType: 'current'
      artifactName: 'Artifact-$(imageName)'
      targetPath: '$(Pipeline.Workspace)'

#  - task: DownloadPackage@1
#    inputs:
#      packageType: 'npm'
#      feed: '3e0295ab-3dd6-43ce-86af-16273f5f1b23/733a8840-9cef-412b-9bb0-8947825ed8b7'
#      view: '4e4e8545-8f17-43b5-96e7-7bd672f8cebd'
#      definition: 'a4b9c615-31e5-4a66-9567-8b05ea4e9eca'
#      version: '1.1.0'
#      downloadPath: '$(System.ArtifactsDirectory)'

  - task: DownloadPackageLiliya@1
    inputs:
      packageType: 'npm'
      feed: '3e0295ab-3dd6-43ce-86af-16273f5f1b23/733a8840-9cef-412b-9bb0-8947825ed8b7'
      view: '4e4e8545-8f17-43b5-96e7-7bd672f8cebd'
      definition: 'a4b9c615-31e5-4a66-9567-8b05ea4e9eca'
      version: '1.1.0'
      downloadPath: '$(System.ArtifactsDirectory)/L1'