# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none
parameters:
- name: version
  displayName: Version of task used (0 or 1)
  type: number
  default: 0

jobs:

- job: 'DownloadPackageTest_MS_Hosted'
  displayName: 'DownloadPackage MS-Hosted'
  strategy:
    matrix:
      linux:
        imageName: 'ubuntu-latest'
      mac:
        imageName: 'macOS-latest'
      windows:
        imageName: 'windows-latest'

  steps:
#  - task: Maven@3
#    inputs:
#      mavenPomFile: 'pom.xml'
#      mavenOptions: '-Xmx3072m'
#      javaHomeOption: 'JDKVersion'
#      jdkVersionOption: '1.8'
#      jdkArchitectureOption: 'x64'
#      publishJUnitResults: true
#      testResultsFiles: '**/surefire-reports/TEST-*.xml'
#      goals: 'package'

#  - task: DownloadPackage@1
#    inputs:
#      packageType: 'npm'
#      feed: '3e0295ab-3dd6-43ce-86af-16273f5f1b23/733a8840-9cef-412b-9bb0-8947825ed8b7'
#      view: '4e4e8545-8f17-43b5-96e7-7bd672f8cebd'
#      definition: 'a4b9c615-31e5-4a66-9567-8b05ea4e9eca'
#      version: '1.1.0'
#      downloadPath: '$(System.ArtifactsDirectory)'

  - task: DownloadPackage@1
    displayName: 'DownloadPackage V1 - NPM'
    condition: ${{eq(parameters.version, 1)}}
    inputs:
      packageType: 'npm'
      feed: '3e0295ab-3dd6-43ce-86af-16273f5f1b23/733a8840-9cef-412b-9bb0-8947825ed8b7'
      view: '4e4e8545-8f17-43b5-96e7-7bd672f8cebd'
      definition: 'a4b9c615-31e5-4a66-9567-8b05ea4e9eca'
      version: '1.0.3'
      downloadPath: '$(System.ArtifactsDirectory)/L1'
  - task: DownloadPackage@1
    displayName: 'DownloadPackage V1 - nuget'
    condition: ${{eq(parameters.version, 1)}}
    inputs:
      packageType: 'nuget'
      feed: '3e0295ab-3dd6-43ce-86af-16273f5f1b23/733a8840-9cef-412b-9bb0-8947825ed8b7'
      view: 
      definition: '41b41b5d-742a-472c-af6c-7fe1518dfaf1'
      version: '2.0.123'
      downloadPath: '$(System.ArtifactsDirectory)/L2'
  - task: DownloadPackageLisa@0
    condition: ${{eq(parameters.version, 0)}}
    displayName: 'Download Package V0 - Dapper'
    inputs:
      feed: '/cbd9f23e-c788-4d0a-babd-4d154e451333'
      definition: '3901d1f7-c35a-47bd-bbf8-d884cb27c9c3'
      version: '2.0.123'
      downloadPath: '$(System.ArtifactsDirectory)/L2'
  - task: DownloadPackageLisa@0
    condition: ${{eq(parameters.version, 0)}}
    displayName: 'Download Package V0 - Serilog'
    inputs:
      feed: '/cbd9f23e-c788-4d0a-babd-4d154e451333'
      definition: '32ce54f0-d184-4a62-bc15-3d83a3521126'
      version: '2.2.0'
      downloadPath: '$(System.ArtifactsDirectory)/L3'

- job: 'DownloadPackageTest_Self_Hosted'
  displayName: 'DownloadPackage Self-Hosted'
  pool: Default

  steps:
  - task: DownloadPackage@1
    displayName: 'DownloadPackage V1 - NPM'
    condition: ${{eq(parameters.version, 1)}}
    inputs:
      packageType: 'npm'
      feed: '3e0295ab-3dd6-43ce-86af-16273f5f1b23/733a8840-9cef-412b-9bb0-8947825ed8b7'
      view: '4e4e8545-8f17-43b5-96e7-7bd672f8cebd'
      definition: 'a4b9c615-31e5-4a66-9567-8b05ea4e9eca'
      version: '1.0.3'
      downloadPath: '$(System.ArtifactsDirectory)/L1'
  - task: DownloadPackage@1
    displayName: 'DownloadPackage V1 - nuget'
    condition: ${{eq(parameters.version, 1)}}
    inputs:
      packageType: 'nuget'
      feed: '3e0295ab-3dd6-43ce-86af-16273f5f1b23/733a8840-9cef-412b-9bb0-8947825ed8b7'
      view: 
      definition: '41b41b5d-742a-472c-af6c-7fe1518dfaf1'
      version: '2.0.123'
      downloadPath: '$(System.ArtifactsDirectory)/L2'
  - task: DownloadPackageLisa@0
    condition: ${{eq(parameters.version, 0)}}
    displayName: 'Download Package V0 - Dapper'
    inputs:
      feed: '/cbd9f23e-c788-4d0a-babd-4d154e451333'
      definition: '3901d1f7-c35a-47bd-bbf8-d884cb27c9c3'
      version: '2.0.123'
      downloadPath: '$(System.ArtifactsDirectory)/L2'
  - task: DownloadPackageLisa@0
    condition: ${{eq(parameters.version, 0)}}
    displayName: 'Download Package V0 - Serilog'
    inputs:
      feed: '/cbd9f23e-c788-4d0a-babd-4d154e451333'
      definition: '32ce54f0-d184-4a62-bc15-3d83a3521126'
      version: '2.2.0'
      downloadPath: '$(System.ArtifactsDirectory)/L3'